// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_creation_timestamp_state_type::UserCreationTimestampState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `user_creation_timestamp_state`.
///
/// Obtain a handle from the [`UserCreationTimestampStateTableAccess::user_creation_timestamp_state`] method on [`super::RemoteTables`],
/// like `ctx.db.user_creation_timestamp_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_creation_timestamp_state().on_insert(...)`.
pub struct UserCreationTimestampStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<UserCreationTimestampState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `user_creation_timestamp_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UserCreationTimestampStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UserCreationTimestampStateTableHandle`], which mediates access to the table `user_creation_timestamp_state`.
    fn user_creation_timestamp_state(&self) -> UserCreationTimestampStateTableHandle<'_>;
}

impl UserCreationTimestampStateTableAccess for super::RemoteTables {
    fn user_creation_timestamp_state(&self) -> UserCreationTimestampStateTableHandle<'_> {
        UserCreationTimestampStateTableHandle {
            imp: self
                .imp
                .get_table::<UserCreationTimestampState>("user_creation_timestamp_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UserCreationTimestampStateInsertCallbackId(__sdk::CallbackId);
pub struct UserCreationTimestampStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UserCreationTimestampStateTableHandle<'ctx> {
    type Row = UserCreationTimestampState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserCreationTimestampState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UserCreationTimestampStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserCreationTimestampStateInsertCallbackId {
        UserCreationTimestampStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UserCreationTimestampStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UserCreationTimestampStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserCreationTimestampStateDeleteCallbackId {
        UserCreationTimestampStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UserCreationTimestampStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<UserCreationTimestampState>("user_creation_timestamp_state");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}
pub struct UserCreationTimestampStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UserCreationTimestampStateTableHandle<'ctx> {
    type UpdateCallbackId = UserCreationTimestampStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UserCreationTimestampStateUpdateCallbackId {
        UserCreationTimestampStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UserCreationTimestampStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UserCreationTimestampState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserCreationTimestampState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `identity` unique index on the table `user_creation_timestamp_state`,
/// which allows point queries on the field of the same name
/// via the [`UserCreationTimestampStateIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_creation_timestamp_state().identity().find(...)`.
pub struct UserCreationTimestampStateIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserCreationTimestampState, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserCreationTimestampStateTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `user_creation_timestamp_state`.
    pub fn identity(&self) -> UserCreationTimestampStateIdentityUnique<'ctx> {
        UserCreationTimestampStateIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserCreationTimestampStateIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<UserCreationTimestampState> {
        self.imp.find(col_val)
    }
}
