// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminFixDeployedCollectiblesArgs {}

impl From<AdminFixDeployedCollectiblesArgs> for super::Reducer {
    fn from(args: AdminFixDeployedCollectiblesArgs) -> Self {
        Self::AdminFixDeployedCollectibles
    }
}

impl __sdk::InModule for AdminFixDeployedCollectiblesArgs {
    type Module = super::RemoteModule;
}

pub struct AdminFixDeployedCollectiblesCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_fix_deployed_collectibles`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_fix_deployed_collectibles {
    /// Request that the remote module invoke the reducer `admin_fix_deployed_collectibles` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_admin_fix_deployed_collectibles`] callbacks.
    fn admin_fix_deployed_collectibles(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `admin_fix_deployed_collectibles`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AdminFixDeployedCollectiblesCallbackId`] can be passed to [`Self::remove_on_admin_fix_deployed_collectibles`]
    /// to cancel the callback.
    fn on_admin_fix_deployed_collectibles(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> AdminFixDeployedCollectiblesCallbackId;
    /// Cancel a callback previously registered by [`Self::on_admin_fix_deployed_collectibles`],
    /// causing it not to run in the future.
    fn remove_on_admin_fix_deployed_collectibles(
        &self,
        callback: AdminFixDeployedCollectiblesCallbackId,
    );
}

impl admin_fix_deployed_collectibles for super::RemoteReducers {
    fn admin_fix_deployed_collectibles(&self) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "admin_fix_deployed_collectibles",
            AdminFixDeployedCollectiblesArgs {},
        )
    }
    fn on_admin_fix_deployed_collectibles(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> AdminFixDeployedCollectiblesCallbackId {
        AdminFixDeployedCollectiblesCallbackId(self.imp.on_reducer(
            "admin_fix_deployed_collectibles",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::AdminFixDeployedCollectibles {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_admin_fix_deployed_collectibles(
        &self,
        callback: AdminFixDeployedCollectiblesCallbackId,
    ) {
        self.imp
            .remove_on_reducer("admin_fix_deployed_collectibles", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `admin_fix_deployed_collectibles`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_admin_fix_deployed_collectibles {
    /// Set the call-reducer flags for the reducer `admin_fix_deployed_collectibles` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn admin_fix_deployed_collectibles(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_admin_fix_deployed_collectibles for super::SetReducerFlags {
    fn admin_fix_deployed_collectibles(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("admin_fix_deployed_collectibles", flags);
    }
}
